### ISSUE TITLE
Lifetime Donation Option

### ISSUE THREAD

**Issue by reedickulus** [wako-app/wako#108]
I thought I remember in the app there were two options to donate to become a “lifetime premium” user. I think the options were $6.99 or $8.99 (option to select based on what the app is worth).

However I don’t see this option any more? Am I confusing this option with another app? I know there is an option on the website to donate 10 Euros, but what happened to these in-app purchase options? I was finally looking forward to unlocking the pro version after pay day this Friday, but now can’t find it.

I may be confused here and thinking of another app, but was this option ever available?

**Comment by JumBay** [comment]
Yes, those options were presents, but now the lifetime contribution is only on paypal

**Comment by free4ever** [comment]
Is there anyway you can bring this back? I was saving my Google Play balance to purchase the Lifetime option, but now it's gone.

**Comment by JumBay** [comment]
Sorry but I won't, Google or Apple are fees are too high. I roughly get a bit more than 50% of what you pay to them. That's why I prefer [PayPal](https://wako.app/donate).

**Comment by free4ever** [comment]
That's a fair point, but you can always raise the lifetime subscription fee to 20 euros in the app so it is double what you would normally request via PayPal. That way you give people the option to pay within the app if they have a Google Play balance (a lot of people in the US do Google surveys and have a Play balance that they want to spend). You will get lifetime donations that you normally would not get, and also because people are much more comfortable paying through a channel that seems more legitimate than sending money to a random email address.

**Comment by JumBay** [comment]
Fair enough. The option is now back at a higher price. Clear wako's cache in wako's settings to see it

**Comment by free4ever** [comment]
Great, thanks for adding it back.
