### ISSUE TITLE
Change loading up next 

### ISSUE THREAD

**Issue by SamJongenelen** [wako-app/wako#114]
The flow to open something takes pretty long. 
When I know which show and episode I want to watch, the whole trakt appears to be requeried.
Is there any way to speed up the process? 
Perhaps with caching the whole list, and unobtrusively update it?

Thank you for the great app.
Sent from pixel2

**Comment by JumBay** [comment]
Everything is already cached (you can try to open wako in airplane mode). But this part can be very slow because of the way trakt is built. There is no progress API route, then wako needs to do a lot of requests to retrieve data. I've already asked help on their [Github](https://github.com/trakt/api-help/issues/102), but their answer is still not perfect and I think it's in their interest to implement this feature to will avoid every developer to reinvent the wheel.  

Even on trakt's website if you have watched a lot of TV shows it takes time to load. 

I did improve the cache system though in the latest build (couple minutes ago), it should be faster when you mark something as watched and the list is refreshed, but still not perfect.

To speed up this part you could remove shows you don't watch it will retrieve less data on trakt and do fewer queries as well

**Comment by SamJongenelen** [comment]
@JumBay I just installed it - and it is a lot faster indeed!
