### ISSUE TITLE
[Enhancement] Combine IMDb & Trakt Ratings

### ISSUE THREAD

**Issue by tjamieg** [wako-app/wako#136]
When browsing movies and tv shows, the star rating currently uses Trakt as it’s main data source, which can sometimes be misleading, especially when only a few people have rated it via Trakt.

Can I suggest that you combine both the IMDb and Trakt ratings for this figure?

![A873ACB6-44CA-46AC-BD94-1F066910A3D5](https://user-images.githubusercontent.com/48328397/82501972-11380780-9aee-11ea-9644-7bcedff016be.jpeg)

So in the example provided, a more appropriate rating would be 4.6 (as per the workings out below)

= (IMDb votes + Trakt votes) / Total votes
= ((4.3 x 645) + (6.3 x 121)) / (645 + 121)
= (2773.5 + 762.3) / 766
= 3535.8 / 766
= 4.6

Implementing this would also enhance the credibility of the results when using the ‘rating’ filter.

**Comment by JumBay** [comment]
Unfortunately that's not possible because trakt API doesn't provide this information. When you are on an item detail page a request is made on IMDb to request that information. This couldn't be done on the list page cause it's too much resources to query. And even rating filter won't work cause it's done on trakt API
